# Generated by Django 5.0.6 on 2024-06-08 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_venta_fecha_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 16, 55, 23, 501450)),
        ),
    ]
