# Generated by Django 5.0.6 on 2024-06-08 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venta_alter_detalleventa_venta_delete_venta1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 18, 27, 27, 869636)),
        ),
    ]
